### ISSUE TITLE
Can't install vine after upgrading to pip 19.0

### ISSUE THREAD

**Issue by grski** [celery/vine#28]
Basically my pip install fails on this package and throws:
```
Collecting vine>=1.1.3 (from amqp<3.0,>=2.1.4->kombu<5.0,>=4.2.0->celery==4.2.1->-r requirements/app.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/62/dd/e30f828a39914626d67876b987d6fc47616b64de680cd0f746fc9c8aab47/vine-1.2.0-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
```

My requirements:
```
uwsgi==2.0.17
django==2.1.3
djangorestframework==3.9.0
psycopg2-binary==2.7.6
paramiko==2.4.2
django-storages==1.7.1
celery==4.2.1
pyaml==17.12.1
pytest-sftpserver==1.2.0
```
Dockerfile:
```
FROM python:3.7-alpine as application
COPY requirements/app.txt /app/requirements/app.txt
WORKDIR /app/
RUN apk update
RUN apk add --no-cache --virtual .build-deps \
        gcc \
        linux-headers \
        postgresql-dev \
        musl-dev \
        build-base \
        libffi-dev \
        python3-dev

RUN pip3.7 install --upgrade pip && \
        pip3.7 install -r requirements/app.txt --no-cache-dir
```

Rolling back to 18.1 makes it work correctly, so it's fine for now, but I think it might be worth looking into.

**Comment by clokep** [comment]
I suspect that this is pypa/pip#6163, but I'm not 100% sure.

**Comment by rodcarroll** [comment]
It's pypa/pip#6158

**Comment by thedrow** [comment]
So not us?

**Comment by clokep** [comment]
Probably worth trying again with 19.0.2 that was released.

**Comment by grski** [comment]
After upgrading to 19.0.3 it works. Thank you, this should be closed.
