### ISSUE TITLE
'dict' object has no attribute 'index'

### ISSUE THREAD

**Issue by t-io** [celery/vine#5]
From time to time this error shows up. I'm not sure if this is vine related or celery in general.
```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/app/builtins.py", line 80, in unlock_chord
    ret = j(timeout=3.0, propagate=True)
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/result.py", line 693, in join
    interval=interval, no_ack=no_ack, on_interval=on_interval,
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/result.py", line 178, in get
    self.maybe_throw(callback=callback)
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/result.py", line 294, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/app/.heroku/python/lib/python3.5/site-packages/celery/result.py", line 287, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.5/site-packages/vine/promises.py", line 213, in throw
    reraise(type(exc), exc, tb)
  File "/app/.heroku/python/lib/python3.5/site-packages/vine/five.py", line 176, in reraise
    raise value
celery.exceptions.ChordError: AttributeError("'dict' object has no attribute 'index'",)
```

**Comment by auvipy** [comment]
closing for now
